---
- name: Gather LSB Facts
  ansible.builtin.setup:
    filter: lsb

- name: End role if Host Operating System is not Ubuntu
  ansible.builtin.meta: end_role
  when: ansible_facts.lsb.id != 'Ubuntu'

- name: End role if Host Operating System is not an Ubuntu LSB Release
  ansible.builtin.meta: end_role
  when: ansible_facts.lsb.release not in ubuntu_pro_lts_releases
